services:
  reverse-proxy:
    image: traefik:v2.7
    command:
      "--api.insecure=true"
      "--providers.docker"
      "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock